export const tr = {
  common_online: 'Çevrimiçi',
  common_offline: 'Çevrimdışı',
  common_online_count: ({count}) => `${count} kullanıcı çevrimiçi`,
  common_minute: 'dk',
  common_message: 'mesaj',
  common_no: 'Hayır',
  common_yes: 'Evet',
  common_cancel: 'İptal Et',
  common_save: 'Kaydet',
  common_back: 'Geri Dön',
  common_ok: 'Tamam',
  common_home: 'Ana Sayfaya Dön',
  common_skip: 'Geç (Skip)',
  common_continue: 'Devam Et',
  common_leave: 'Ayrıl',
  common_cancel_alt: 'Vazgeç',

  nav_profile: 'Profil',
  nav_history: 'Geçmiş Sohbetler',
  nav_matchmaking: 'Eşleşme Aranıyor',
  nav_home_title: 'QChat',

  welcome_app_name: 'QChat',
  welcome_tagline: 'Anonim · Şifreli · Sınırsız',
  welcome_step1_title: 'Eşleş',
  welcome_step1_desc: 'Havuza katıl',
  welcome_step2_title: 'Sohbet Et',
  welcome_step2_desc: 'Şifreli mesaj',
  welcome_step3_title: 'Bitir',
  welcome_step3_desc: 'Skip veya tamamla',
  welcome_btn_register: 'Kayıt Ol',
  welcome_btn_login: 'Giriş Yap',
  welcome_feature_intl_title: 'Uluslararası Mod',
  welcome_feature_intl_desc: 'Farklı ülkelerden kullanıcılarla İngilizce eşleş',
  welcome_feature_local_title: 'Yerel Mod',
  welcome_feature_local_desc: 'Kendi ülkendeki kullanıcılarla tanış',
  welcome_feature_enc_title: 'AES-256 Şifreleme',
  welcome_feature_enc_desc: 'Her mesaj uçtan uca şifrelenir',
  welcome_feature_timer_title: 'Süreli Eşleşme',
  welcome_feature_timer_desc: '2dk zorunlu, ardından Skip (maks 5dk)',
  mode_local_badge: (f) => `${f} Kendi Dilinde`,

  login_title: 'Giriş Yap',
  login_subtitle: 'QChat hesabınıza erişin',
  login_email_label: 'E-posta Adresi',
  login_email_placeholder: 'ornek@email.com',
  login_password_label: 'Şifre',
  login_password_placeholder: '••••••••',
  login_button_loading: 'Giriş Yapılıyor...',
  login_button_idle: 'Giriş Yap',
  login_no_account: 'Hesabınız yok mu?',
  login_register_link: 'Hemen Kayıt Ol',
  login_error_not_found: 'Bu e-posta ile kayıtlı hesap bulunamadı.',
  login_error_mismatch: 'Hesap bilgileri eşleşmiyor.',

  register_title: 'Hesap Oluştur',
  register_subtitle: 'Eşleşmeye başlamak için kaydolun (16+)',
  register_nickname_label: 'Takma Ad',
  register_nickname_placeholder: 'CyberTraveler',
  register_age_label: 'Yaş (16+)',
  register_age_placeholder: '20',
  register_email_label: 'E-posta',
  register_email_placeholder: 'ornek@email.com',
  register_password_label: 'Şifre',
  register_password_placeholder: '••••••••',
  register_button_loading: 'Kayıt Yapılıyor...',
  register_button_idle: 'Kayıt Ol & Başla',
  register_has_account: 'Zaten hesabınız var mı?',
  register_login_link: 'Giriş Yap',
  register_validation_fill_all: 'Lütfen tüm alanları doldurun.',
  register_validation_age: '16 yaş altı kullanıcılar hesap oluşturamaz.',
  register_error_email_taken: 'Bu e-posta zaten kullanılıyor.',
  register_error_nickname_taken: 'Bu takma ad başka biri tarafından kullanılıyor.',

  home_greeting: 'Hoşgeldin,',
  home_stat_chats: 'Sohbet',
  home_stat_minutes: 'Dakika',
  home_stat_reputation: 'Liyakat',
  home_recent_title: 'Son Eşleşmeler',
  home_recent_empty: 'Henüz eşleşme yok',
  home_mode_title: 'Eşleşme Modu',
  home_match_btn: 'Eşleşmeye Başla',
  home_match_badge: 'AES-256',
  home_history_meta: ({duration, count}) => `${duration} dk · ${count} mesaj`,

  matchmaking_connecting: 'Havuza bağlanılıyor...',
  matchmaking_scanning: 'Yeni kullanıcılar taranıyor...',
  matchmaking_scanning_intl: 'Farklı ülkelerden kullanıcılar taranıyor...',
  matchmaking_scanning_local: 'Kendi ülkenden kullanıcı taranıyor...',
  matchmaking_waiting_rematch: 'Karşınızın onayı bekleniyor...',
  matchmaking_rematch_found: 'Daha önce eşleştiğiniz biri bulundu...',
  matchmaking_rematch_rejected: 'Karşı taraf kabul etmedi. Yeni kullanıcılar taranıyor...',
  matchmaking_rematch_timeout: 'Süre doldu. Yeni kullanıcılar taranıyor...',
  matchmaking_rematch_cancelled: 'Karşı taraf vazgeçti. Yeni kullanıcılar taranıyor...',
  matchmaking_generating_key: 'Oturum anahtarı oluşturuluyor...',
  matchmaking_blocked_reputation: ({rep}) => `Liyakat puanın ${rep} olduğu için eşleşemezsin.`,
  matchmaking_blocked_leaves: 'Erken ayrılma hakkın doldu. 3 gün bekleyin.',
  matchmaking_mandatory_intl: 'English is mandatory.',
  matchmaking_mandatory_local: 'İlk 2 dk zorunludur.',
  matchmaking_incoming_rematch: 'Biri sizinle tekrar eşleşmek istiyor...',
  matchmaking_modal_title: 'Tekrar Eşleşme',
  matchmaking_modal_desc: 'Bu kişiyle daha önce eşleştiniz. Aktif kullanıcı bulunamadı.\nTekrar sohbet etmek ister misiniz?',
  matchmaking_label_mode: 'Mod',
  matchmaking_value_intl: 'Uluslararası',
  matchmaking_value_local: 'Yerel',
  matchmaking_label_duration: 'Zorunlu Süre',
  matchmaking_value_duration: '2 Dakika',
  matchmaking_label_max: 'Maksimum',
  matchmaking_value_max: '5 Dakika',
  matchmaking_label_security: 'Güvenlik',
  matchmaking_value_security: 'AES-256',

  chat_no_active: 'Aktif sohbet bulunamadı.',
  chat_partner_meta: ({country, mode}) => `${country} · ${mode}`,
  chat_skip_locked: 'Skip Kilitli',
  chat_skip_confirm_title: 'Sonraki Kişiye Geç',
  chat_skip_confirm_desc: 'Bu sohbeti sonlandırıp hemen yeni biriyle eşleşmek istiyor musunuz?',
  chat_leave_title: 'Sohbetten Ayrıl',
  chat_leave_desc: 'Sohbeti tamamen kapatmak ve ana sayfaya dönmek istiyor musunuz?',
  chat_ended_title: 'Sohbet Sonlandırıldı',
  chat_ended_desc: 'Karşı taraf sohbetten ayrıldı.',
  chat_timeout_title: 'Süreniz Doldu!',
  chat_timeout_desc: '5 dakikalık sohbet süreniz sona erdi. Yeni biriyle eşleşebilirsiniz.',
  chat_warning_1min: 'Süreniz dolmak üzere! 1 dakika kaldı.',
  chat_placeholder_intl: 'Type in English (Encrypted)...',
  chat_placeholder_local: 'Mesajınızı yazın (Şifreli)...',
  chat_mode_intl: 'English Only',
  chat_mode_local: 'Lokal',
  chat_timer_skip_active: 'Skip aktif',
  chat_timer_skip_locked: ({time}) => `Skip: ${time}`,

  profile_title: 'Profil',
  profile_age_verified: ({age}) => `Yaş Doğrulandı: ${age}`,
  profile_rep_title: 'Liyakat Puanı',
  profile_rep_leaves: ({left}) => `Kalan erken ayrılma hakkı: ${left} / 3`,
  profile_rep_status: 'Durum:',
  profile_rep_blocked: 'Eşleşme engelli (70 altı)',
  profile_rep_active: 'Aktif',
  profile_section_account: 'Hesap Ayarları',
  profile_country_change: 'Ülke Değiştir',
  profile_age_info: 'Yaş Bilgisi',
  profile_age_value: ({age}) => `${age} Yaşında`,
  profile_security: 'Güvenlik',
  profile_security_val: 'AES-256',
  profile_database: 'Veritabanı',
  profile_database_val: 'Firebase',
  profile_firebase_setup: 'Firebase Kurulumu',
  profile_logout: 'Çıkış Yap',

  history_title: 'Geçmiş Sohbetler',
  history_empty: 'Henüz tamamlanmış bir sohbet yok.',
  history_global: 'Global',
  history_local: 'Lokal',
  history_duration: ({duration}) => `${duration} dk`,
  history_messages: ({count}) => `${count} mesaj`,

  country_modal_title: 'Ülke Seçin',
  country_modal_search_placeholder: 'Ülke ara...',

  firebase_modal_title: 'Firebase Kurulum',
  firebase_modal_subtitle: 'Firebase Console > Web uygulaması > Config nesnesini yapıştırın',
  firebase_modal_label: 'Firebase Config (JSON)',
  firebase_modal_placeholder: '{"apiKey": "AIzaSy...", "projectId": "..."}',
  firebase_modal_validation_empty: 'Lütfen Firebase config JSON girin.',
  firebase_modal_validation_fields: 'JSON "apiKey" ve "projectId" alanlarını içermelidir.',
  firebase_modal_validation_invalid: 'Geçersiz JSON formatı.',
  firebase_modal_saved_title: 'Kaydedildi',
  firebase_modal_saved_desc: 'Firebase yapılandırması kaydedildi. Değişikliklerin etkili olması için uygulamayı yeniden başlatın.',
  firebase_modal_reset: 'Sıfırla',
  firebase_modal_save_restart: 'Kaydet & Yeniden Başlat',
  firebase_modal_reset_done: 'Varsayılan yapılandırmaya dönüldü.',

  header_subtitle: 'Eşleşme Portalı',
};

export const en = {
  common_online: 'Online',
  common_offline: 'Offline',
  common_online_count: ({count}) => `${count} users online`,
  common_minute: 'min',
  common_message: 'msg',
  common_no: 'No',
  common_yes: 'Yes',
  common_cancel: 'Cancel',
  common_save: 'Save',
  common_back: 'Go Back',
  common_ok: 'OK',
  common_home: 'Return to Home',
  common_skip: 'Skip',
  common_continue: 'Continue',
  common_leave: 'Leave',
  common_cancel_alt: 'Cancel',

  nav_profile: 'Profile',
  nav_history: 'Chat History',
  nav_matchmaking: 'Searching for Match',
  nav_home_title: 'QChat',

  welcome_app_name: 'QChat',
  welcome_tagline: 'Anonymous \u00b7 Encrypted \u00b7 Unlimited',
  welcome_step1_title: 'Match',
  welcome_step1_desc: 'Join the pool',
  welcome_step2_title: 'Chat',
  welcome_step2_desc: 'Encrypted message',
  welcome_step3_title: 'Finish',
  welcome_step3_desc: 'Skip or complete',
  welcome_btn_register: 'Register',
  welcome_btn_login: 'Log In',
  welcome_feature_intl_title: 'International Mode',
  welcome_feature_intl_desc: 'Match with users from different countries in English',
  welcome_feature_local_title: 'Local Mode',
  welcome_feature_local_desc: 'Meet users from your own country',
  welcome_feature_enc_title: 'AES-256 Encryption',
  welcome_feature_enc_desc: 'Every message is end-to-end encrypted',
  welcome_feature_timer_title: 'Timed Matching',
  welcome_feature_timer_desc: '2min mandatory, then Skip (max 5min)',
  mode_local_badge: (f) => `${f} Native`,

  login_title: 'Log In',
  login_subtitle: 'Access your QChat account',
  login_email_label: 'Email Address',
  login_email_placeholder: 'example@email.com',
  login_password_label: 'Password',
  login_password_placeholder: '\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022',
  login_button_loading: 'Logging in...',
  login_button_idle: 'Log In',
  login_no_account: "Don't have an account?",
  login_register_link: 'Register Now',
  login_error_not_found: 'No account found with this email.',
  login_error_mismatch: 'Account information does not match.',

  register_title: 'Create Account',
  register_subtitle: 'Register to start matching (16+)',
  register_nickname_label: 'Nickname',
  register_nickname_placeholder: 'CyberTraveler',
  register_age_label: 'Age (16+)',
  register_age_placeholder: '20',
  register_email_label: 'Email',
  register_email_placeholder: 'example@email.com',
  register_password_label: 'Password',
  register_password_placeholder: '\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022',
  register_button_loading: 'Registering...',
  register_button_idle: 'Register & Start',
  register_has_account: 'Already have an account?',
  register_login_link: 'Log In',
  register_validation_fill_all: 'Please fill all fields.',
  register_validation_age: 'Users under 16 cannot create an account.',
  register_error_email_taken: 'This email is already in use.',
  register_error_nickname_taken: 'This nickname is already in use.',

  home_greeting: 'Welcome,',
  home_stat_chats: 'Chats',
  home_stat_minutes: 'Minutes',
  home_stat_reputation: 'Reputation',
  home_recent_title: 'Recent Matches',
  home_recent_empty: 'No matches yet',
  home_mode_title: 'Match Mode',
  home_match_btn: 'Start Matching',
  home_match_badge: 'AES-256',
  home_history_meta: ({duration, count}) => `${duration} min \u00b7 ${count} messages`,

  matchmaking_connecting: 'Connecting to pool...',
  matchmaking_scanning: 'Scanning for new users...',
  matchmaking_scanning_intl: 'Scanning users from different countries...',
  matchmaking_scanning_local: 'Scanning users from your country...',
  matchmaking_waiting_rematch: 'Waiting for approval...',
  matchmaking_rematch_found: 'Someone you matched with before was found...',
  matchmaking_rematch_rejected: 'Other party declined. Scanning for new users...',
  matchmaking_rematch_timeout: 'Time expired. Scanning for new users...',
  matchmaking_rematch_cancelled: 'Other side backed out. Scanning for new users...',
  matchmaking_generating_key: 'Creating session key...',
  matchmaking_blocked_reputation: ({rep}) => `You cannot match because your reputation is ${rep}.`,
  matchmaking_blocked_leaves: 'Your early leave rights are exhausted. Wait 3 days.',
  matchmaking_mandatory_intl: 'English is mandatory.',
  matchmaking_mandatory_local: 'First 2 min are mandatory.',
  matchmaking_incoming_rematch: 'Someone wants to rematch with you...',
  matchmaking_modal_title: 'Rematch',
  matchmaking_modal_desc: 'You matched with this person before. No active users found.\nWould you like to chat again?',
  matchmaking_label_mode: 'Mode',
  matchmaking_value_intl: 'International',
  matchmaking_value_local: 'Local',
  matchmaking_label_duration: 'Mandatory',
  matchmaking_value_duration: '2 Minutes',
  matchmaking_label_max: 'Maximum',
  matchmaking_value_max: '5 Minutes',
  matchmaking_label_security: 'Security',
  matchmaking_value_security: 'AES-256',

  chat_no_active: 'No active chat found.',
  chat_partner_meta: ({country, mode}) => `${country} \u2022 ${mode}`,
  chat_skip_locked: 'Skip Locked',
  chat_skip_confirm_title: 'Go to Next Person',
  chat_skip_confirm_desc: 'Do you want to end this chat and immediately match with someone new?',
  chat_leave_title: 'Leave Chat',
  chat_leave_desc: 'Do you want to completely close the chat and return to the home screen?',
  chat_ended_title: 'Chat Ended',
  chat_ended_desc: 'The other party left the chat.',
  chat_timeout_title: 'Your Time is Up!',
  chat_timeout_desc: 'Your 5 minute chat session has ended. You can match with someone new.',
  chat_warning_1min: 'Your time is almost up! 1 minute left.',
  chat_placeholder_intl: 'Type in English (Encrypted)...',
  chat_placeholder_local: 'Type your message (Encrypted)...',
  chat_mode_intl: 'English Only',
  chat_mode_local: 'Local',
  chat_timer_skip_active: 'Skip active',
  chat_timer_skip_locked: ({time}) => `Skip: ${time}`,

  profile_title: 'Profile',
  profile_age_verified: ({age}) => `Age Verified: ${age}`,
  profile_rep_title: 'Reputation Score',
  profile_rep_leaves: ({left}) => `Early leave rights left: ${left} / 3`,
  profile_rep_status: 'Status:',
  profile_rep_blocked: 'Matching blocked (below 70)',
  profile_rep_active: 'Active',
  profile_section_account: 'Account Settings',
  profile_country_change: 'Change Country',
  profile_age_info: 'Age Info',
  profile_age_value: ({age}) => `${age} Years Old`,
  profile_security: 'Security',
  profile_security_val: 'AES-256',
  profile_database: 'Database',
  profile_database_val: 'Firebase',
  profile_firebase_setup: 'Firebase Setup',
  profile_logout: 'Log Out',

  history_title: 'Chat History',
  history_empty: 'No completed chats yet.',
  history_global: 'Global',
  history_local: 'Local',
  history_duration: ({duration}) => `${duration} min`,
  history_messages: ({count}) => `${count} messages`,

  country_modal_title: 'Select Country',
  country_modal_search_placeholder: 'Search country...',

  firebase_modal_title: 'Firebase Setup',
  firebase_modal_subtitle: 'Firebase Console > Web app > Paste the config object',
  firebase_modal_label: 'Firebase Config (JSON)',
  firebase_modal_placeholder: '{"apiKey": "AIzaSy...", "projectId": "..."}',
  firebase_modal_validation_empty: 'Please enter Firebase config JSON.',
  firebase_modal_validation_fields: 'JSON must contain "apiKey" and "projectId" fields.',
  firebase_modal_validation_invalid: 'Invalid JSON format.',
  firebase_modal_saved_title: 'Saved',
  firebase_modal_saved_desc: 'Firebase configuration saved. Restart the app for changes to take effect.',
  firebase_modal_reset: 'Reset',
  firebase_modal_save_restart: 'Save & Restart',
  firebase_modal_reset_done: 'Returned to default configuration.',

  header_subtitle: 'Match Portal',
};
